### ISSUE TITLE
[App V2, iOS] Paper Trails window only partially visible

### ISSUE THREAD

**Issue by jeroenvollenbrock** [Dijker/nu.dijker.PaperTrails#16]
iOS app V2 (101 - and previous versions) on iPhone SE
The lowermost part of the window is not visible in the app - when trying to scroll, the screen is blank:

![2017-12-07 12 11 20](https://user-images.githubusercontent.com/29979509/33758295-f352f902-dbfd-11e7-87bf-5af0c0c0abc9.png)

![2017-12-07 12 11 09](https://user-images.githubusercontent.com/29979509/33758301-f6394fa4-dbfd-11e7-8060-deb39e8febb5.png)

Originally reported by @cbho in https://github.com/athombv/homey/issues/2032

**Comment by Dijker** [comment]
Although not fully fixed I have a look into fixing it for smaller screens. 
also hope some help from https://github.com/athombv/homey/issues/2134
