### ISSUE TITLE
[V.0.3.3] Send log to developer not available under "Settings" - "Apps"

### ISSUE THREAD

**Issue by cbho** [Dijker/nu.dijker.PaperTrails#20]
Homey 1.5.6-rc.7
PaperTrails 0.3.3

**What did you try to achieve?**
Send the log to the developer as described under "Maintenance":
"Go to Settings - Apps: Hold the ALT key and click Send Log to Developer)"

**What was the result?**
At the "Apps" page, the "Send Log to Developer" becomes available for most other apps - just not PaperTrails:
![image](https://user-images.githubusercontent.com/29979509/34468068-12bc6bb4-ef01-11e7-958c-740030151f45.png)

**What did you expect as result?**
That it did ;-)

**Any other remarks**
Clicked the "Send Log to Developer" under the apps "Maintenance" page - so perhaps a log arrived?

**Comment by Dijker** [comment]
Thanks!! 
Nice you already found it and installed it as Developer. 
It is just approved and I will do some final testing before publishing!

No link for the side-loaded App is as expected (Will appear when you install from the store) The Button should have worked (and also from the mobile App already ), but suddenly it stopped...

I will look into it if it is something in the App or at the Athom Backend....

**Comment by Dijker** [comment]
Don't know why but it works again as expected.
