### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tangodelta73** [Dijker/nu.dijker.PaperTrails#38]
**What is your Homey version (Settings - System), your App version (Settings-Apps) ?**

Homey 3.0.1
PaperTrails 0.60.0
Send Log to Developer: xxx-xxxx-xxxx

**What did you try to achieve?**
Crash Homey when opened in iphone 7

**What was the result?**
...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by yormedia** [comment]
What is your Homey version (Settings - System), your App version (Settings-Apps) ?

Homey 4.2.0-rc.9
PaperTrails 0.6.3
Send Log to Developer: xxx-xxxx-xxxx

What did you try to achieve?
Nothing yet, could not see it in the flow, then realized it has crashed after install

What was the result?
App will crash immediatly even when rebooting the Homey

What did you expect as result?
To work ;-)

Any other remarks
Maybe the latest Homey release is not handling it well?

**Comment by yormedia** [comment]
Just tested again by closing all homey instances on pc and phone and installed again, waited a few seconds and it was working.

**Comment by Dijker** [comment]
Thanks for your report, 
Closing all Settings Pages including on the PC before restarting the App is the current solution. 
I Informed Athom about a glitch in the code starting Apps. This is in The Homey core and I can's fix this. Waiting for Athom ;-)
