### ISSUE TITLE
New HOMEY Pro 2023

### ISSUE THREAD

**Issue by CyberSponk** [Dijker/nu.dijker.PaperTrails#51]
Hi,

will be there a Version for new HOMEY Pro 2023 in future avaible? At the moment the App-Store shows that the App is not compatible with the new HOMEY Pro.

Kind Regards,
Nick

**Comment by djbakker** [comment]
> Hi,
> 
> will be there a Version for new HOMEY Pro 2023 in future avaible? At the moment the App-Store shows that the App is not compatible with the new HOMEY Pro.
> 
> Kind Regards, Nick

Same question. Update should me nice. ;-)

**Comment by n808** [comment]
Ditto, I absolutely depend on this app for debugging flows!

**Comment by ptahbe** [comment]
Yes. Please update this app for the new Homey Pro.

**Comment by hummelmose** [comment]
Yes please - This is my primary log utility - I need it for my Homey Pro 2023.

**Comment by SA0BJW** [comment]
Almost all of my flows has cards depending on this app. I have the new Homey pro 2023 delivered, and just waiting for an update of this app so I can migrate to the new Homey!

**Comment by hummelmose** [comment]
> Almost all of my flows has cards depending on this app. I have the new Homey pro 2023 delivered, and just waiting for an update of this app so I can migrate to the new Homey!

Do you use at Syslog - I use Graylog, and found Simple (Sys) Log that is currently in beta. It works perfect for syslog systems. Here's a link if interested: https://homey.app/da-dk/app/nl.nielsdeklerk.log/Simple-(Sys)-Log/test/

**Comment by SA0BJW** [comment]
> Do you use at Syslog - I use Graylog, and found Simple (Sys) Log that is currently in beta. It works perfect for syslog systems. Here's a link if interested: https://homey.app/da-dk/app/nl.nielsdeklerk.log/Simple-(Sys)-Log/test/

Thank you.
I think I can solve my issue by generating a mosquitto message (MQTT Client app) and in Node-Red (R-Pi) convert the message into a syslog message and send it to my syslogserver.

**Comment by hummelmose** [comment]
> > Do you use at Syslog - I use Graylog, and found Simple (Sys) Log that is currently in beta. It works perfect for syslog systems. Here's a link if interested: https://homey.app/da-dk/app/nl.nielsdeklerk.log/Simple-(Sys)-Log/test/
> 
> Thank you. I think I can solve my issue by generating a mosquitto message (MQTT Client app) and in Node-Red (R-Pi) convert the message into a syslog message and send it to my syslogserver.

Why would you do that - The link I just sent you do communicate directly with syslog servers.

**Comment by SA0BJW** [comment]
> Why would you do that - The link I just sent you do communicate directly with syslog servers.
Ok, I will try it!

I have another issue, I need to replace the "http request flow card" app too.  I use it to send text messages from Homey to a text display. That app hasn´t been updated for 3 years, so I don´t think it will be updated for the pro 2023.
I can solve this in the same way, by using MQTT and convert to http.

**Comment by hummelmose** [comment]
> > Why would you do that - The link I just sent you do communicate directly with syslog servers.
> > Ok, I will try it!
> 
> I have another issue, I need to replace the "http request flow card" app too. I use it to send text messages from Homey to a text display. That app hasn´t been updated for 3 years, so I don´t think it will be updated for the pro 2023. I can solve this in the same way, by using MQTT and convert to http.

That can be done with Homeyscript.

**Comment by Dijker** [comment]
Guys this is not a forum: discuss here: https://community.homey.app/
